import subprocess

#subprocess.run(["python", "00ConfigureDirInfo.py"], shell=True)
subprocess.run(["python","00MakeDir.py"], shell=True)
subprocess.run(["python","01aRMMatching.py"], shell=True)
subprocess.run(["python","01bRMMapping.py"], shell=True)
subprocess.run(["python","02aFilterReferencePoints.py"], shell=True)
subprocess.run(["python","02bConsiderReferencePoints.py"], shell=True)
subprocess.run(["python","02cMapReferencePoints.py"], shell=True)
subprocess.run(["python","03CalculateBLOS.py"], shell=True)
subprocess.run(["python","04aDensitySensitivity.py"], shell=True)
subprocess.run(["python","04bDensitySensitivityPlot.py"], shell=True)
subprocess.run(["python","05aTempSensitivity.py"], shell=True)
subprocess.run(["python","05bTempSensitivityPlot.py"], shell=True)
subprocess.run(["python","06UncertaintyAnalysis.py"], shell=True)
